/*
 * rach
 *
 * This is an an organization app. it helps keeps books and other items in location.
 *
 * API version: 1.0.0
 * Contact: aravind@agastya-library.in
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	AddObj(http.ResponseWriter, *http.Request)
	GetObj(http.ResponseWriter, *http.Request)
	UpdateObj(http.ResponseWriter, *http.Request)
}
// ObjectApiRouter defines the required methods for binding the api requests to a responses for the ObjectApi
// The ObjectApiRouter implementation should parse necessary information from the http request,
// pass the data to a ObjectApiServicer to perform the required actions, then write the service results to the http response.
type ObjectApiRouter interface { 
	DelObj(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	AddObj(context.Context, Object) (ImplResponse, error)
	GetObj(context.Context) (ImplResponse, error)
	UpdateObj(context.Context) (ImplResponse, error)
}


// ObjectApiServicer defines the api actions for the ObjectApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ObjectApiServicer interface { 
	DelObj(context.Context) (ImplResponse, error)
}
