/*
 * rach
 *
 * This is an an organization app. it helps keeps books and other items in location.
 *
 * API version: 1.0.0
 * Contact: aravind@agastya-library.in
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// AddObj - Adds a new object to home
func (s *DefaultApiService) AddObj(ctx context.Context, object Object) (ImplResponse, error) {
	// TODO - update AddObj with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	//return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddObj method not implemented")
}

// GetObj - 
func (s *DefaultApiService) GetObj(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetObj with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetObj method not implemented")
}

// UpdateObj - 
func (s *DefaultApiService) UpdateObj(ctx context.Context) (ImplResponse, error) {
	// TODO - update UpdateObj with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateObj method not implemented")
}
