/*
 * rach
 *
 * This is an an organization app. it helps keeps books and other items in location.
 *
 * API version: 1.0.0
 * Contact: aravind@agastya-library.in
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ObjectApiService is a service that implements the logic for the ObjectApiServicer
// This service should implement the business logic for every endpoint for the ObjectApi API.
// Include any external packages or services that will be required by this service.
type ObjectApiService struct {
}

// NewObjectApiService creates a default api service
func NewObjectApiService() ObjectApiServicer {
	return &ObjectApiService{}
}

// DelObj - delete an existing obj
func (s *ObjectApiService) DelObj(ctx context.Context) (ImplResponse, error) {
	// TODO - update DelObj with the required logic for this service method.
	// Add api_object_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	//return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DelObj method not implemented")
}
