/*
 * rach
 *
 * This is an an organization app. it helps keeps books and other items in location.
 *
 * API version: 1.0.0
 * Contact: aravind@agastya-library.in
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/aparavind/rach/server/go"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := openapi.NewDefaultApiService()
	DefaultApiController := openapi.NewDefaultApiController(DefaultApiService)

	ObjectApiService := openapi.NewObjectApiService()
	ObjectApiController := openapi.NewObjectApiController(ObjectApiService)

	router := openapi.NewRouter(DefaultApiController, ObjectApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
